### ISSUE TITLE
Logical test gives result in scientific format

### ISSUE THREAD

**Issue by ariful19** [bulbulamd/Tasks#1]
আপনার লজিক্যাল টেস্টের উভয় সল্যুশনে পূর্ণ সংখ্যার পরিবর্তে **scientific format** এ ফলাফল দেখায়। এমন একটি সল্যুশন দরকার যা থেকে আমরা সবগুলো ডিজিট সহ **পূর্ণাঙ্গ যোগফল** পাবো। যেমন -**1212123456121212345612121234561212123456121212345612**

Tasks/Laravel-API-and-logic-test/app/Http/Controllers/LogicTestController.php

**Comment by bulbulamd** [comment]
Dear Sir,

I have tried to resolve issue of scientific format and integer 64 bit
limitation. And updated on git for logical test.


Regards
Bulbul Ahmed
01710417080




2018-03-21 12:47 GMT+06:00 ariful19 <notifications@github.com>:

**Comment by ariful19** [comment]
জনাব, 
এ বাপারে আপনি সফল। php এর এই চমৎকার feature আমাদের c#, java, javascript ইত্যাদিতে নেই। ফলে পুরা যোগফল ভিন্ন লজিকে করতে হয়। যদিও ল্যাঙ্গুয়েজ গুলতে বিশেষ ফিচার দ্বারা কাজটা করা হয়।
জাঝাকাল্লাহ!
